# Generated by Django 5.2.1 on 2025-05-15 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(verbose_name=50)),
                ('number', models.CharField(verbose_name=10)),
                ('city', models.CharField(verbose_name=50)),
                ('state', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(verbose_name=11)),
                ('birth_date', models.DateField()),
                ('function', models.CharField(verbose_name=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='employee.address')),
            ],
        ),
    ]
