# Generated by Django 5.2.1 on 2025-06-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
