# Generated by Django 5.2.1 on 2025-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='function',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
